version: "3.7"
services:
  app:
    image: flycherami/php7.4-node16:latest
    ports:
      - "80:80"
    volumes:
      - "./dist:/app"
    working_dir: /app
  node:
    image: flycherami/php7.4-node16:latest
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    working_dir: /app
    command: bash -c "npm install && npm run dev"
