version: "3.7"
services:
  apache:
    image: registry.gitlab.cher-ami.tv/docker/docker-images/php:7.4
    ports:
      - "${DOCKER_APACHE_PORT:-4321}:80"
    volumes:
      - "./dist:/app"
    working_dir: /app
  node:
    image: node:16.16.0
    ports:
      - "${DOCKER_NODE_PORT:-3000}:3000"
    volumes:
      - "./:/app"
    working_dir: /app
    tty: true
