version: "3.7"
services:
  app:
    image: registry.gitlab.cher-ami.tv/docker/docker-images/php-node:7.4-16
    ports:
      - "${DOCKER_APACHE_PORT:-4321}:80"
    volumes:
      - "./dist:/app"
    working_dir: /app
  node:
    image: registry.gitlab.cher-ami.tv/docker/docker-images/php-node:7.4-16
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    working_dir: /app
    command: bash -c "npm install --legacy-peer-deps"
